version: '2.1'
services:
  chouette-postgres:
    build:
      context: postgres
      dockerfile: Dockerfile
    ports: 
      - "5433:5432"
    environment:
      -  POSTGRES_PASSWORD=chouette
      -  POSTGRES_USER=chouette
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  chouette-redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
  chouette-iev:
    build:
      context: iev
      dockerfile: Dockerfile
    ports:
     - "8081:8080"
     - "9991:9990"
    volumes:
     - ./data/referentials:/opt/jboss/referentials
    links:
     - chouette-postgres:chouette-postgres
  chouette-gui:
    build:
      context: chouette2
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data/referentials:/home/chouette/referentials
      - ./data/logs:/home/chouette/chouette2/log
    links:
      - chouette-iev:chouette-iev
      - chouette-postgres:chouette-postgres
      - chouette-redis:chouette-redis
